import type { Prompt } from "@/lib/types"

export const PROMPTS: Prompt[] = [
  // 1-line easy
  {
    id: "1-easy-0",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `let count = 0`,
  },
  {
    id: "1-easy-1",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `const ok = true`,
  },
  {
    id: "1-easy-2",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `const name = "Alice"`,
  },
  {
    id: "1-easy-3",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `const items: string[] = []`,
  },
  {
    id: "1-easy-4",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `let isLoading = false`,
  },

  // 1-line medium
  {
    id: "1-medium-0",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const slug = "Hello World".trim().toLowerCase().replace(/\\s+/g, "-")`,
  },
  {
    id: "1-medium-1",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const sum = [1, 2, 3].reduce((a, b) => a + b, 0)`,
  },
  {
    id: "1-medium-2",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const ids = users.map((u) => u.id)`,
  },
  {
    id: "1-medium-3",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const first = items.find((x) => x.active) ?? null`,
  },
  {
    id: "1-medium-4",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const [count, setCount] = useState(0)`,
  },

  // 1-line hard
  {
    id: "1-hard-0",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `const tap = <T,>(x: T, fn: (x: T) => void): T => (fn(x), x)`,
  },
  {
    id: "1-hard-1",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `type Flatten<T> = T extends (infer U)[] ? U : T`,
  },
  {
    id: "1-hard-2",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `type Keys<T> = T extends object ? keyof T : never`,
  },
  {
    id: "1-hard-3",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `const pick = <T, K extends keyof T>(obj: T, key: K): T[K] => obj[key]`,
  },
  {
    id: "1-hard-4",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `type Awaited<T> = T extends Promise<infer U> ? U : T`,
  },

  // 2-line easy
  {
    id: "2-easy-0",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const now = new Date()\nconst iso = now.toISOString()`,
  },
  {
    id: "2-easy-1",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const xs = [1, 2, 3]\nconst len = xs.length`,
  },
  {
    id: "2-easy-2",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const name = "world"\nconst greeting = \`Hello, \${name}!\``,
  },
  {
    id: "2-easy-3",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const x = 5\nconst y = x * 2 + 1`,
  },
  {
    id: "2-easy-4",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const a = 10\nconst b = a + 5`,
  },

  // 2-line medium
  {
    id: "2-medium-0",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const isEven = (n: number) => n % 2 === 0\nconst evens = [1, 2, 3, 4].filter(isEven)`,
  },
  {
    id: "2-medium-1",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const words = "a b  c".trim().split(/\\s+/)\nconst csv = words.join(",")`,
  },
  {
    id: "2-medium-2",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const doubled = [1, 2, 3].map((n) => n * 2)\nconst sum = doubled.reduce((a, b) => a + b, 0)`,
  },
  {
    id: "2-medium-3",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const toggle = () => setOpen((prev) => !prev)\nconst isActive = open && !disabled`,
  },
  {
    id: "2-medium-4",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const sorted = [...items].sort((a, b) => a.localeCompare(b))\nconst first = sorted[0]`,
  },

  // 2-line hard
  {
    id: "2-hard-0",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `type Fn<T, R> = (arg: T) => R\nconst apply = <T, R>(fn: Fn<T, R>, x: T): R => fn(x)`,
  },
  {
    id: "2-hard-1",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))\nvoid sleep(10)`,
  },
  {
    id: "2-hard-2",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `type Result<T> = { ok: true; data: T } | { ok: false; error: string }\nconst success = <T,>(data: T): Result<T> => ({ ok: true, data })`,
  },
  {
    id: "2-hard-3",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>\ntype User = Optional<{ id: string; name: string }, "id">`,
  },
  {
    id: "2-hard-4",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `const keys = <T extends object>(o: T) => Object.keys(o) as (keyof T)[]\nconst k = keys({ a: 1, b: 2 })`,
  },

  // 3-line easy
  {
    id: "3-easy-0",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `const a = 1\nconst b = 2\nconst c = a + b`,
  },
  {
    id: "3-easy-1",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `let total = 0\ntotal += 2\ntotal += 3`,
  },
  {
    id: "3-easy-2",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `const user = { name: "Alice", age: 30 }\nconst { name, age } = user\nconst info = \`\${name} is \${age}\``,
  },
  {
    id: "3-easy-3",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `function greet(name: string) {\n  return \`Hello, \${name}!\`\n}`,
  },
  {
    id: "3-easy-4",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `const colors = ["red", "green", "blue"]\nconst first = colors[0]\nconst last = colors.at(-1)`,
  },

  // 3-line medium
  {
    id: "3-medium-0",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `const clamp = (n: number, min: number, max: number) =>\n  Math.min(max, Math.max(min, n))\nconst clamped = clamp(10, 0, 5)`,
  },
  {
    id: "3-medium-1",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `const toTitle = (s: string) => s[0]!.toUpperCase() + s.slice(1)\nconst hello = toTitle("hello")\nconst world = toTitle("world")`,
  },
  {
    id: "3-medium-2",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `const fetchUser = async (id: string) =>\n  fetch(\`/api/users/\${id}\`).then((r) => r.json())\nconst user = await fetchUser("123")`,
  },
  {
    id: "3-medium-3",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `useEffect(() => {\n  document.title = \`Count: \${count}\`\n}, [count])`,
  },
  {
    id: "3-medium-4",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `type GroupedItems = Record<string, Item[]>\nconst grouped: GroupedItems = {}\nitems.forEach((item) => (grouped[item.type] ??= []).push(item))`,
  },

  // 3-line hard
  {
    id: "3-hard-0",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `type DeepPartial<T> = {\n  [K in keyof T]?: DeepPartial<T[K]>\n}`,
  },
  {
    id: "3-hard-1",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `const compose = <A, B, C>(f: (a: A) => B, g: (b: B) => C) =>\n  (x: A): C => g(f(x))\nconst toStr = compose((n: number) => n * 2, String)`,
  },
  {
    id: "3-hard-2",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `type Action = "inc" | "dec" | "reset"\nconst reduce = (s: number, a: Action) =>\n  a === "reset" ? 0 : s + (a === "inc" ? 1 : -1)`,
  },
  {
    id: "3-hard-3",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `function exhaustive(x: never): never {\n  throw new Error(\`Unexpected value: \${x}\`)\n}`,
  },
  {
    id: "3-hard-4",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `type Nullable<T> = T | null | undefined\nconst isDefined = <T,>(x: Nullable<T>): x is T => x != null\nconst compact = <T,>(xs: Nullable<T>[]) => xs.filter(isDefined)`,
  },
]
