import type { Prompt } from "@/lib/types"

export const PROMPTS: Prompt[] = [
  {
    id: "1-easy-0",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `let count = 0`,
  },
  {
    id: "1-easy-1",
    language: "ts",
    difficulty: "easy",
    lines: 1,
    code: `const ok = true`,
  },
  {
    id: "1-medium-0",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const slug = "Hello World".trim().toLowerCase().replace(/\s+/g, "-")`,
  },
  {
    id: "1-medium-1",
    language: "ts",
    difficulty: "medium",
    lines: 1,
    code: `const n = Number.parseInt("42", 10)`,
  },
  {
    id: "1-hard-0",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `const uniq = <T,>(xs: T[]) => Array.from(new Set(xs))`,
  },
  {
    id: "1-hard-1",
    language: "ts",
    difficulty: "hard",
    lines: 1,
    code: `const hex = (n: number) => n.toString(16).padStart(2, "0")`,
  },

  {
    id: "2-easy-0",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const now = new Date()\nconsole.log(now.toISOString())`,
  },
  {
    id: "2-easy-1",
    language: "ts",
    difficulty: "easy",
    lines: 2,
    code: `const xs = [1, 2, 3]\nconsole.log(xs.length)`,
  },
  {
    id: "2-medium-0",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const isEven = (n: number) => n % 2 === 0\nconsole.log([1, 2, 3, 4].filter(isEven))`,
  },
  {
    id: "2-medium-1",
    language: "ts",
    difficulty: "medium",
    lines: 2,
    code: `const words = "a b  c".trim().split(/\s+/)\nconsole.log(words.join(","))`,
  },
  {
    id: "2-hard-0",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `type User = { id: string; name: string }\nconst getId = (u: User) => u.id`,
  },
  {
    id: "2-hard-1",
    language: "ts",
    difficulty: "hard",
    lines: 2,
    code: `const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))\nvoid sleep(10)`,
  },

  {
    id: "3-easy-0",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `const xs = [1, 2, 3]\nconst sum = xs.reduce((a, n) => a + n, 0)\nconsole.log(sum)`,
  },
  {
    id: "3-easy-1",
    language: "ts",
    difficulty: "easy",
    lines: 3,
    code: `let total = 0\ntotal += 2\ntotal += 3`,
  },
  {
    id: "3-medium-0",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `const clamp = (n: number, a: number, b: number) => Math.min(b, Math.max(a, n))\nconst x = clamp(10, 0, 5)\nconsole.log(x)`,
  },
  {
    id: "3-medium-1",
    language: "ts",
    difficulty: "medium",
    lines: 3,
    code: `const toTitle = (s: string) => s[0]!.toUpperCase() + s.slice(1)\nconst out = toTitle("hello")\nconsole.log(out)`,
  },
  {
    id: "3-hard-0",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `function clamp(n: number, min: number, max: number) {\n  return Math.min(max, Math.max(min, n))\n}`,
  },
  {
    id: "3-hard-1",
    language: "ts",
    difficulty: "hard",
    lines: 3,
    code: `const pipe = <A, B, C>(ab: (a: A) => B, bc: (b: B) => C) => (a: A) => bc(ab(a))\nconst inc = (n: number) => n + 1\nconsole.log(pipe(inc, inc)(0))`,
  },
]
